spring:
  datasource:
    url: ${SPRING_DATASOURCE_ENROLLMENT_URL}
    username: ${ENROLLMENT_DB_USER}
    password: ${ENROLLMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

resilience4j:
  circuitbreaker:
    instances:
      courseService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      courseService:
        max-attempts: 3
        wait-duration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,busrefresh
  health:
    circuitbreakers:
      enabled: true